project_id = "pblovwlejwgnplhhnudv"

[functions.sync-tracking]
verify_jwt = false

[functions.sync-onlyfans]
verify_jwt = false

[functions.debug-api]
verify_jwt = false

[functions.sync-orchestrator]
verify_jwt = false

[functions.sync-account]
verify_jwt = false

[functions.sync-scheduler]
verify_jwt = false
