
ALTER TABLE public.tracking_links
  ADD COLUMN IF NOT EXISTS cost_type TEXT,
  ADD COLUMN IF NOT EXISTS cost_value DECIMAL(12,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cost_total DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cvr DECIMAL(8,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cpl_real DECIMAL(8,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cpc_real DECIMAL(8,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS arpu DECIMAL(8,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS profit DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS roi DECIMAL(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'NO_DATA';
