
ALTER TABLE public.accounts
  ADD COLUMN IF NOT EXISTS ltv_total DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ltv_tips DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ltv_subscriptions DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ltv_messages DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ltv_posts DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ltv_last_30d DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ltv_last_7d DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ltv_updated_at TIMESTAMPTZ;
